tags:
  [
  ]
bundles:
  [
    {
      frame: "bundle_2",
      tags: [
        {
          id: 5,
          corners: [
            [ 0.0365,  0.0365, 0.0],
            [ 0.0365,  0.0000, 0.0],
            [ 0.0000,  0.0000, 0.0]
          ]
        },
        {
          id: 7,
          corners : [
            [ 0.0365, -0.0065, 0.0],
            [ 0.0365, -0.0425, 0.0],
            [ 0.0000, -0.0425, 0.0]
          ]
        },
        {
          id: 0,
          corners : [
            [ 0.0610,  0.1220, 0.0],
            [ 0.0610,  0.0610, 0.0],
            [ 0.0000,  0.0610, 0.0]
          ]
        },
        {
          id: 6,
          corners : [
            [ 0.0610, -0.0670, 0.0],
            [ 0.0610, -0.1230, 0.0],
            [ 0.0000, -0.1230, 0.0]
          ]
        },
        {
          id: 3,
          corners : [
            [ 0.1900, 0.1220, 0.0],
            [ 0.1900, 0.0000,0.0],
            [ 0.0680, 0.0000, 0.0]
          ]
        },
        {
          id: 1,
          corners : [
            [ 0.1900, -0.0065, 0.0],
            [ 0.1900, -0.1230, 0.0],
            [ 0.0680, -0.1230, 0.0]
          ]
        }
      ]
    }
  ]

# Marker corner order
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
